// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantApp;

#nullable disable

namespace RestaurantApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221206024341_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("RestaurantApp.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Ammount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("RestaurantApp.Customer", b =>
                {
                    b.Property<byte>("TableNumber")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("NumberOfPersons")
                        .HasColumnType("tinyint");

                    b.HasKey("TableNumber");

                    b.HasIndex("BillId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("RestaurantApp.FoodItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("RestaurantApp.Customer", b =>
                {
                    b.HasOne("RestaurantApp.Bill", "Bill")
                        .WithMany("Custom")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("RestaurantApp.FoodItems", b =>
                {
                    b.HasOne("RestaurantApp.Bill", null)
                        .WithMany("Items")
                        .HasForeignKey("BillId");
                });

            modelBuilder.Entity("RestaurantApp.Bill", b =>
                {
                    b.Navigation("Custom");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
